# catppuccin mocha
$rosewater = rgb(f5e0dc)
$mauve     = rgb(cba6f7)
$red       = rgb(f38ba8)
$blue      = rgb(89b4fa)
$lavender  = rgb(b4befe)
$text      = rgb(cdd6f4)
$subtext0  = rgb(a5adc8)
$surface0  = rgb(313244)
$base      = rgb(1e1e2e)

$font = JetBrains Mono

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 6
    noise = 0.0117
    brightness = 0.6
    color = $base
}

input-field {
    monitor =
    size = 300, 55
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35
    outer_color = $mauve $blue 45deg
    inner_color = $surface0
    font_color = $text
    font_family = $font
    fade_on_empty = false
    placeholder_text = <span foreground="##a5adc8"><i>logged in as $USER</i></span>
    check_color = $lavender
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    rounding = 10
    position = 0, -30
    halign = center
    valign = center
}

# time
label {
    monitor =
    text = $TIME
    color = $text
    font_size = 90
    font_family = $font
    position = 0, 120
    halign = center
    valign = center
}

# date
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    color = $subtext0
    font_size = 20
    font_family = $font
    position = 0, 40
    halign = center
    valign = center
}
