require("modules.env")
require("modules.monitors")
require("modules.appearance")
require("modules.animations")
require("modules.input")
require("modules.binds")
require("modules.rules")
require("modules.autostart")
